language: java
jdk:
    - openjdk13

addons:
    sonarcloud:
        organization: giuseppelasco17
        token: a02c36ef4a9d044f0edb1703955e856afa8070fc
script:
    - ant build
    - sonar-scanner